### PR TITLE
[daemon] Implement ebpf loading/unloading on config change

### LINKED ISSUE #77: internal: implement loading/unloading of ebpf functions in daemon

### PR DESCRIPTION
**Pull request by Mr-Kanister**
Closes #77

### CODE REVIEW

**Comment by BenediktZinn** [comment]
LGTM
+ we should talk about what folders are currently in use with all dev's and delete the deprecated ones at some point...

**Comment by fhilgers** [comment]
Yes we should, we currently have to keep the example folders because I do not think everything is ported to the other yet, right?

**Comment by Mr-Kanister** [comment]
Most of it is ported, but I don't know about the example-ebpf one. As that one is linked to the other ones, too, it was not possible to delete only some folders. We have to delete all at one point, I think.

**Comment by fhilgers** [comment]
Also toms new PR adds something to `example`, `example-common` and `example-ebfp`

**Pull request merged**
