### PR TITLE
Add command to nix flake to run SBOM generation

### LINKED ISSUE #30: Manage Sbom generation through nix
## Developer Story
1. As a Developer
2. I want to reduce the locations where dependencies come from
3. So that the build is more consistent (developer and ci) and the dependencies are more visible

## Acceptance criteria
* Install the python dependencies via nix
* Create a program output in the flake so i can run `nix run .#generateSbom` or similar to generate the sbom

### PR DESCRIPTION
**Pull request by Mr-Kanister**
The SBOM generation can now be called via `nix run .#generateSbom`.

Closes #30

### CODE REVIEW

**Review by der-whity — COMMENTED** [review]
for me the command gets stuck in generate_sbom.py in the function "generate_nix_sbom" while running the subprocess

**Comment by Mr-Kanister** [comment]
What does `nix build .#toolsSbom` do? It should result in an "./result" bom file the top level directory.

3 Nov 2024, 17:27 by ***@***.***:

**Comment by fhilgers** [comment]
So nix build results in a script under `./result/bin/generate-sbom.sh` which can be run to generate the sbom with all the paths to the dependencies set.

Nix run is just a convenience for running that script directly.

Generating the sbom takes a while, where does it get stuck?

**Comment by fhilgers** [comment]
More or less the whole point of that change is so that we can just call `nix run `.#generateSbom` in CI without manually keeping up with changing dependencies:

e.g. we switch to a new cyclonedx version, then we would need to look at ci scripts, figure out how we get the new version there. With this, ci just needs nix installed and the output of locally running and ci always matches up.

**Comment by Mr-Kanister** [comment]
> So nix build results in a script under ./result/bin/generate-sbom.sh
Yes, but not with the command I wanted him to run. This command just produces the nix sbom while getting info about the process and if it produces any errors. You won't get those via the python script which calls `nix build ./toolsSbom` itself.

**Pull request merged**
