### PR TITLE
[UI] Navigation, Home, Config and Visualization Screen

### PR DESCRIPTION
**Pull request by luca-dot-sh**
This commit adds 4 screens: home, visualization, configuration and about. 
Visualization uses actual counter from backend to display packages per second.
Configuration is a mock screen that only implements a basic design for integrating with the rest in the next sprint.
About is a placeholder for now so that the menu does not look as empty, but we can maybe replace it with another screen if we need one or change the home screen design.

### CODE REVIEW

**Comment by luca-dot-sh** [comment]
Here is a video:
[pr79.webm](https://github.com/user-attachments/assets/ccbb00ce-0b28-4dca-9247-c6f2b034349a)

**Comment by fhilgers** [comment]
LGTM, smaller fixes we can defer to next sprint, like for example the duplicate client binary `rust/client/src/main.rs`. This was moved previously to `rust/client/bin/cli.rs`, I think commiting the old file was probably by accident.

**Review by fhilgers — APPROVED** [review]

**Comment by fhilgers** [comment]
I'll add the dependencies to our document.

**Comment by Mr-Kanister** [comment]
Closes #43

**Comment by luca-dot-sh** [comment]
Closes #47

**Pull request merged**
