### PR TITLE
Implement SBOM creation

### LINKED ISSUE #9: bill of materials

### PR DESCRIPTION
**Pull request by Mr-Kanister**
For the generation of the SBOMS we use **cargo-cyclonedx** for our rust dependencies and **bombon** for our nix dependencies. The kotlin dependencies are managed by **cyclonedx-gradle-plugin** and were implemented elsewhere. For the merging we use **cyclonedx-cli**.

Closes #9

### CODE REVIEW

**Review by fhilgers — APPROVED** [review]
LGTM

**Comment by fhilgers** [comment]
We do not need the pyproject.toml anymore, as cyclonedx-cli is used, right?

This can happen in a future ticket.

**Comment by Mr-Kanister** [comment]
> We do not need the pyproject.toml anymore, as cyclonedx-cli is used, right?

Yes, they are not needed. We deleted them but the change got lost while reverting and rebasing.

**Comment by fhilgers** [comment]
Makes sense, we'll fix it in next sprint @Mr-Kanister

**Pull request merged**
